### ISSUE TITLE
Whish List (because Christmas and so on,...)

### ISSUE THREAD

**Issue by TolotosRhodan** [czenker/lively-epsilon#1]
1. Production, I´d love a hook or something so i can actually "produce" like CPU ships. (with order definition and so on, so a hook for functions would be nice)

2. Ships AI, it would be nice if there would be a code to tell CPU ships (Trader/Merchants/Miners) if there is a CPU ship which they are could colliding with and getting both ships stuck, they first both turn into opposing heading and second fly "right" to avoid contact. this should work for ships who try to dock "on" each other and also getting stuck. After this they should go back to their AI mission (trader/merchants/miner/whatever)

3.Set Comms of the ships to default. Right now they all say "Hello World". The hook is nice, but should be "optional" for the enrich function.

**Comment by czenker** [comment]
1. `conf.produces` can be a function now instead of the table

2. this is probably something, that should be taken care in the game itself.

3. I removed that whole `enrich` to have every feature opt-in. You can use `Ship:withComms(ship)` now.
